apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-app
  labels:
    app: text-generation-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-generation-app
  template:
    metadata:
      labels:
        app: text-generation-app
    spec:
      containers:
      - name: text-generation-app
        image: gcr.io/iac1-424123/gemini1:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          value: "AIzaSyC9uXy92lQX2knCanapxwVfEHRixkpG8rM"
---
apiVersion: v1
kind: Service
metadata:
  name: text-generation-app
spec:
  selector:
    app: text-generation-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
